#!/bin/bash

# Example of running python script in a batch mode

#SBATCH -J oi_gmi
#SBATCH --qos=debug
#SBATCH --constraint="cssro&cas"
#SBATCH --account=s1043
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=12
#SBATCH --mem=180G
##SBATCH -t 4:00:00
#SBATCH -o oi_gmi-%j.out
#SBATCH -e oi_gmi-%j.err
#SBATCH --no-requeue

# Load software

# Run python script
/discover/nobackup/asouri/miniconda3/bin/python3 driver.py
