# set your python executable path
python_bin: '/discover/nobackup/asouri/miniconda3/bin/python3'

# to run the job on debug queue
debug: False

# algorithm (LASSO, DNN)
algorithm: DNN

# number of jobs
num_job: 12

# set the path of CTM netcdf files (either relative or absolute)
ctm_dir: '/discover/nobackup/asouri/PROJECTS/PO3_ACMAP/ozonerates/minds/'

# model type
ctm_type: MINDS

# model frequency (monthly or daily)
ctm_freq: monthly

# the sensor name (OMI, TROPOMI)
sensor: 'TROPOMI'

# set the sat dir
sat_dir_no2: '/discover/nobackup/asouri/PROJECTS/PO3_ACMAP/ozonerates/trop_no2/'
sat_dir_hcho: '/discover/nobackup/asouri/PROJECTS/PO3_ACMAP/ozonerates/trop_hcho/'

# starting date (YYYY-MM) and ending date (YYYY-MM) (the end point will be considered)
start_date: '2019-07'
end_date:   '2019-07'

# output folder for PDF reports
output_pdf_dir: './report_PO3_dnn_LA'

# output folder for NC diags
output_nc_inputparam_dir: './diag_inputparam_tropomi_LA'
output_nc_PO3_dir: './diag_PO3_tropomi_LA'
